
INSERT INTO tb_pessoas (pe_nome, pe_senha, pe_cpf, pe_usuario, pe_flagtipopessoa) VALUES
                                                                                      ('João Silva', 'senha123', '123.456.789-00', 'joaosilva', 'A'),
                                                                                      ('Maria Santos', 'senha456', '987.654.321-00', 'mariasantos', 'C'),
                                                                                      ('Pedro Oliveira', 'senha789', '456.789.123-00', 'pedrooliveira', 'F'),
                                                                                      ('Ana Souza', 'senhaabc', '789.123.456-00', 'anasouza', 'A'),
                                                                                      ('José Pereira', 'senhaxyz', '654.321.987-00', 'josepereira', 'C'),
                                                                                      ('Carla Costa', 'senhajkl', '321.654.987-00', 'carlacosta', 'F'),
                                                                                      ('Fernando Santos', 'senha123', '456.789.123-00', 'fernandosantos', 'A'),
                                                                                      ('Mariana Oliveira', 'senha456', '789.123.456-00', 'marianaoliveira', 'C'),
                                                                                      ('Lucas Pereira', 'senha789', '654.321.987-00', 'lucaspereira', 'F'),
                                                                                      ('Juliana Lima', 'senhaabc', '321.654.987-00', 'julianalima', 'A'),
                                                                                      ('Rodrigo Almeida', 'senhaxyz', '987.654.321-00', 'rodrigoalmeida', 'C'),
                                                                                      ('Patrícia Costa', 'senhajkl', '654.321.987-00', 'patriciacosta', 'F'),
                                                                                      ('Gustavo Oliveira', 'senha123', '321.654.987-00', 'gustavooliveira', 'A'),
                                                                                      ('Aline Silva', 'senha456', '987.654.321-00', 'alinesilva', 'C'),
                                                                                      ('Rafael Santos', 'senha789', '654.321.987-00', 'rafaelsantos', 'F'),
                                                                                      ('Camila Lima', 'senhaabc', '321.654.987-00', 'camilalima', 'A'),
                                                                                      ('Bruno Almeida', 'senhaxyz', '987.654.321-00', 'brunoalmeida', 'C'),
                                                                                      ('Vanessa Costa', 'senhajkl', '654.321.987-00', 'vanessacosta', 'F'),
                                                                                      ('Henrique Oliveira', 'senha123', '321.654.987-00', 'henriqueoliveira', 'A'),
                                                                                      ('Laura Silva', 'senha456', '987.654.321-00', 'laurasilva', 'C'),
                                                                                      ('Paulo Santos', 'senha789', '654.321.987-00', 'paulosantos', 'F'),
                                                                                      ('Carolina Lima', 'senhaabc', '321.654.987-00', 'carolinalima', 'A'),
                                                                                      ('Diego Almeida', 'senhaxyz', '987.654.321-00', 'diegoalmeida', 'C'),
                                                                                      ('Tatiane Costa', 'senhajkl', '654.321.987-00', 'tatianecosta', 'F'),
                                                                                      ('Thiago Oliveira', 'senha123', '321.654.987-00', 'thiagooliveira', 'A'),
                                                                                      ('Fernanda Silva', 'senha456', '987.654.321-00', 'fernandasilva', 'C'),
                                                                                      ('Roberto Santos', 'senha789', '654.321.987-00', 'robertosantos', 'F'),
                                                                                      ('Renata Lima', 'senhaabc', '321.654.987-00', 'renatalima', 'A'),
                                                                                      ('Luciana Almeida', 'senhaxyz', '987.654.321-00', 'lucianaalmeida', 'C'),
                                                                                      ('Marcos Costa', 'senhajkl', '654.321.987-00', 'marcoscosta', 'F'),
                                                                                      ('Patrícia Oliveira', 'senha123', '321.654.987-00', 'patriciaoliveira', 'A'),
                                                                                      ('Ricardo Silva', 'senha456', '987.654.321-00', 'ricardosilva', 'C'),
                                                                                      ('Beatriz Santos', 'senha789', '654.321.987-00', 'beatrizsantos', 'F'),
                                                                                      ('Cristina Lima', 'senhaabc', '321.654.987-00', 'cristinalima', 'A'),
                                                                                      ('Gabriel Almeida', 'senhaxyz', '987.654.321-00', 'gabrielalmeida', 'C'),
                                                                                      ('Daniela Costa', 'senhajkl', '654.321.987-00', 'danielacosta', 'F'),
                                                                                      ('Carlos Oliveira', 'senha123', '321.654.987-00', 'carlosoliveira', 'A'),
                                                                                      ('Amanda Silva', 'senha456', '987.654.321-00', 'amandasilva', 'C'),
                                                                                      ('Josiane Santos', 'senha789', '654.321.987-00', 'josianesantos', 'F'),
                                                                                      ('Eduardo Lima', 'senhaabc', '321.654.987-00', 'eduardolima', 'A'),
                                                                                      ('Tatiana Almeida', 'senhaxyz', '987.654.321-00', 'tatianaalmeida', 'C'),
                                                                                      ('Leandro Costa', 'senhajkl', '654.321.987-00', 'leandrocosta', 'F'),
                                                                                      ('Camila Oliveira', 'senha123', '321.654.987-00', 'camilaoliveira', 'A'),
                                                                                      ('Lucas Silva', 'senha456', '987.654.321-00', 'lucassilva', 'C'),
                                                                                      ('Marina Santos', 'senha789', '654.321.987-00', 'marinasantos', 'F'),
                                                                                      ('Jéssica Lima', 'senhaabc', '321.654.987-00', 'jessicalima', 'A'),
                                                                                      ('Guilherme Almeida', 'senhaxyz', '987.654.321-00', 'guilhermealmeida', 'C'),
                                                                                      ('Isabela Costa', 'senhajkl', '654.321.987-00', 'isabelacosta', 'F'),
                                                                                      ('Renato Oliveira', 'senha123', '321.654.987-00', 'renatooliveira', 'A'),
                                                                                      ('Gabriela Silva', 'senha456', '987.654.321-00', 'gabrielasilva', 'C'),
                                                                                      ('André Santos', 'senha789', '654.321.987-00', 'andresantos', 'F'),
                                                                                      ('Monica Lima', 'senhaabc', '321.654.987-00', 'monicalima', 'A'),
                                                                                      ('Felipe Almeida', 'senhaxyz', '987.654.321-00', 'felipealmeida', 'C'),
                                                                                      ('Elaine Costa', 'senhajkl', '654.321.987-00', 'elainecosta', 'F'),
                                                                                      ('Vinícius Oliveira', 'senha123', '321.654.987-00', 'viniciusoliveira', 'A'),
                                                                                      ('Juliana Silva', 'senha456', '987.654.321-00', 'julianasilva', 'C'),
                                                                                      ('Marcelo Santos', 'senha789', '654.321.987-00', 'marcelosantos', 'F'),
                                                                                      ('Vanessa Lima', 'senhaabc', '321.654.987-00', 'vanessalima', 'A'),
                                                                                      ('Rafael Almeida', 'senhaxyz', '987.654.321-00', 'rafaelalmeida', 'C'),
                                                                                      ('Carolina Costa', 'senhajkl', '654.321.987-00', 'carolinacosta', 'F'),
                                                                                      ('Pedro Oliveira', 'senha123', '321.654.987-00', 'pedrooliveira2', 'A'),
                                                                                      ('Ana Silva', 'senha456', '987.654.321-00', 'anasilva', 'C'),
                                                                                      ('José Santos', 'senha789', '654.321.987-00', 'josesantos', 'F'),
                                                                                      ('Carla Lima', 'senhaabc', '321.654.987-00', 'carlalima', 'A'),
                                                                                      ('Fernando Almeida', 'senhaxyz', '987.654.321-00', 'fernandoalmeida', 'C'),
                                                                                      ('Mariana Costa', 'senhajkl', '654.321.987-00', 'marianacosta', 'F'),
                                                                                      ('Lucas Oliveira', 'senha123', '321.654.987-00', 'lucasoliveira', 'A')

--------------------------------

    INSERT INTO tb_produtos (pro_descricao, pro_valor, pro_quantidade, for_codigo) VALUES
    ('Caneta esferográfica azul', 2.50, 200, 1),
    ('Lápis preto HB', 1.50, 300, 1),
    ('Borracha branca', 1.00, 500, 1),
    ('Caderno capa dura 100 folhas', 15.99, 100, 1),
    ('Folha sulfite A4 - pacote com 500 folhas', 19.99, 50, 1),
    ('Apontador duplo', 3.49, 150, 1),
    ('Marcador de texto amarelo', 4.99, 120, 1),
    ('Cola bastão', 2.99, 180, 1),
    ('Tesoura escolar', 7.50, 80, 1),
    ('Régua plástica 30 cm', 1.75, 200, 1),
    ('Pasta catálogo A4 com 20 envelopes', 12.50, 90, 1),
    ('Grampeador médio', 8.25, 110, 1),
    ('Clips metálicos coloridos - caixa com 100 unidades', 6.99, 130, 1),
    ('Post-it cores neon - bloco com 50 folhas', 3.75, 160, 1),
    ('Envelope pardo ofício - pacote com 50 unidades', 5.50, 140, 1),
    ('Fita corretiva', 4.25, 170, 1),
    ('Pincel marcador permanente preto', 2.85, 190, 1),
    ('Agenda diária 2024', 18.99, 70, 1),
    ('Giz de cera 12 cores', 6.80, 220, 1),
    ('Papel cartão colorido - pacote com 50 folhas', 9.50, 100, 1),
    ('Estojo escolar simples', 5.99, 250, 1),
    ('Durex transparente - rolo com 50 metros', 1.95, 300, 1),
    ('Fichário universitário 4 argolas', 22.75, 60, 1),
    ('Borracha escolar branca', 0.99, 350, 1),
    ('Lápis de cor 24 cores', 14.50, 80, 1),
    ('Pasta suspensa kraft', 8.95, 120, 1);




-----------------------------------------------------------